### ISSUE TITLE
<kbd> isn't being rendered properly

### ISSUE THREAD

**Issue by dylankenneally** [phuocng/frontend-tips#169]
Markdown files containing `<kbd>alt</kbd>` are being rendered as text, including the `<kbd>` and `</kbd>` parts, would expect them to render as keyboard keys such as <kbd>alt</kbd>.

Example: https://getfrontend.tips/move-the-cursor-to-any-position-in-a-macos-command/ (plenty more though)

**Comment by phuocng** [comment]
Will fix it.

**Comment by phuocng** [comment]
Fixed.
