### ISSUE TITLE
<video> isn't being rendered properly

### ISSUE THREAD

**Issue by dylankenneally** [phuocng/frontend-tips#170]
Issue: I've noticed that videos are not being rendered on the site, the markup is rendered instead.

Expectation: the video is rendered (the video file is present).

Example: https://getfrontend.tips/move-the-cursor-to-any-position-in-a-macos-command/ (there are others), renders as

```
The following video demonstrates how I fix a typo in a command using this tip.
<video loop muted controls> <source src="/img/move-cursor-terminal.mp4" type="video/mp4"> </video>
```

**Comment by phuocng** [comment]
Will fix it.

**Comment by phuocng** [comment]
Fixed.
