### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by phuocng** [phuocng/frontend-tips#62]

**Comment by phuoc-ng** [comment]
done!

**Comment by dylankenneally** [comment]
Is the RSS feed still available? 

I can't see one on the site, or in the source for the site - I searched for rss, xml, atom and json without luck.

**Comment by phuocng** [comment]
Will bring it back.

**Comment by phuocng** [comment]
@dylankenneally The feed is now available at https://getfrontend.tips/feed.xml

**Comment by dylankenneally** [comment]
Thanks @phuocng 

Wondering if you are planning to do the same with the other sites you've got running from your git repos?
